update

diff --git a/.github/workflows/immortalwrt_x86_64.yml b/.github/workflows/immortalwrt_x86_64.yml
--- a/.github/workflows/immortalwrt_x86_64.yml
+++ b/.github/workflows/immortalwrt_x86_64.yml
@@ -222,30 +222,30 @@ jobs:
           echo "检测到编译失败,但frpc未启动，跳过 debug 步骤"
         fi
 
-        - name: Check compile
-        if: always()
-        id: compile
-        run: |
-          cd ${{ env.PROJECT }}/bin/targets/*/*
-          if [ -n "$(ls *.img.gz)" ]; then
-            echo "status=success" >> $GITHUB_OUTPUT
-            echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
-            echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
-            echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
-            echo "===========编译成功,准备上传==========="
-            echo "=============生成文件列表============="
-            ls -lh | awk '{print $9, $5}'
-            echo "==============清理文件中============="
-            rm -rf packages *kernel.bin *rootfs* *.json *.tar.zst
-            sleep 2
-            echo "=============上传文件列表============="
-            ls -lh | awk '{print $9, $5}'
-            echo "===================================="
-          else
-            echo "status=failure" >> $GITHUB_OUTPUT
-            echo "===========编译失败,结束工作流==========="
-            exit 1
-          fi
+    - name: Check compile
+      if: always()
+      id: compile
+      run: |
+        cd ${{ env.PROJECT }}/bin/targets/*/*
+        if [ -n "$(ls *.img.gz)" ]; then
+          echo "status=success" >> $GITHUB_OUTPUT
+          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
+          echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
+          echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
+          echo "===========编译成功,准备上传==========="
+          echo "=============生成文件列表============="
+          ls -lh | awk '{print $9, $5}'
+          echo "==============清理文件中============="
+          rm -rf packages *kernel.bin *rootfs* *.json *.tar.zst
+          sleep 2
+          echo "=============上传文件列表============="
+          ls -lh | awk '{print $9, $5}'
+          echo "===================================="
+        else
+          echo "status=failure" >> $GITHUB_OUTPUT
+          echo "===========编译失败,结束工作流==========="
+          exit 1
+        fi
 
     - name : Upload artifact
       uses: actions/upload-artifact@main
