update

diff --git a/.github/workflows/LEDE_x86_64.yml b/.github/workflows/LEDE_x86_64.yml
--- a/.github/workflows/LEDE_x86_64.yml
+++ b/.github/workflows/LEDE_x86_64.yml
@@ -1,8 +1,5 @@
 name: LEDE_x86_64
 
-# Add a button to trigger the workflow
-# sudo -E apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
-# sudo -E apt-get -qq install btop build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils python3-pyelftools python3-setuptools libpython3-dev rsync unzip zlib1g-dev swig aria2 jq subversion qemu-utils ccache rename libelf-dev device-tree-compiler libgnutls28-dev coccinelle libgmp3-dev libmpc-dev libfuse-dev ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libc6-dev libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
 on: 
   repository_dispatch:
   workflow_dispatch:
@@ -14,8 +11,8 @@ env:
   REPO_BRANCH: 'master'  #项目分支
   TARGET_PLATFORM: 'amd64'  #平台架构(amd64/arm64)
   SSH_DEBUG: 'false' #是否开启ssh功能(true/false)
-  SSH_TIME: '30m'    #设置开始编译前暂停时间,可用pkill sleep命令提前继续工作流
-  SSH_TIME2: '2h'    #设置编译报错后暂停时间,可用pkill sleep命令提前继续工作流
+  SSH_TIME: '30'   #单位分钟,设置暂停工作流时间,可用pkill sleep命令提前继续工作流,整个工作流运行时间不能超过6小时
+  SSH_TIME2: '340'   #单位分钟,设置暂停工作流时间,可用pkill sleep命令提前继续工作流,整个工作流运行时间不能超过6小时
   CACHE_CCACHE: 'false'    #是否开启ccache功能(true/false)
   CACHE_CLEAN: 'false'     #是否清除缓存(true/false)
   UPLOAD_ARTIFACT: 'false'   #是否上传到ARTIFACT(true/false)
@@ -65,6 +62,15 @@ jobs:
     - name: Clone source code
       run: |
         git clone --depth 1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} ${{ env.BD_PROJECT }}
+       
+    - name: Free up disk space
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        sudo mkdir -p -m 777 /mnt/openwrt/dl /mnt/openwrt/bin /mnt/openwrt/staging_dir
+        ln -sf /mnt/openwrt/dl openwrt/dl
+        ln -sf /mnt/openwrt/bin openwrt/bin
+        ln -sf /mnt/openwrt/staging_dir openwrt/staging_dir
 
     - name: Cache
       uses: HiGarfield/cachewrtbuild@main
@@ -77,7 +83,7 @@ jobs:
     - name: Update & Install feeds
       working-directory: ./${{ env.BD_PROJECT }}
       run: |
-        mv $GITHUB_WORKSPACE/feeds/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }} $GITHUB_WORKSPACE/${{ env.BD_PROJECT }}/feeds.conf.default
+        mv $GITHUB_WORKSPACE/feeds/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }} $GITHUB_WORKSPACE/${{ env.BD_PROJECT }}/feeds.conf
         ./scripts/feeds update -a
         ./scripts/feeds install -a
         ./scripts/feeds install -a
@@ -115,10 +121,17 @@ jobs:
         if [ -n "${{ secrets.FRPC_CONFIG }}" ]; then
           # 使用提供的frpc配置
           echo "${{ secrets.FRPC_CONFIG }}" > ./frpc.ini
-          chmod +x ./frpc && ./frpc -c ./frpc.ini &
-          echo "================frpc启动成功!================"
-          echo "=========检测为自定义配置,请自行连接ssh========="
-          echo "SSH_SETUP=success" >> $GITHUB_ENV
+          chmod +x ./frpc && ./frpc -c ./frpc.ini > ./frpc.log 2>&1 &
+          sleep 5
+          if grep -q "start proxy success" ./frpc.log; then
+            echo "================frpc启动成功!================"
+            echo "=========检测为自定义配置,请自行连接SSH========="
+            echo "SSH_SETUP=success" >> $GITHUB_ENV
+          else
+            echo "警告:尝试启动frpc失败。请重新配置FRPC_CONFIG字段"
+            echo "==================继续工作流==================="
+            echo "SSH_SETUP=failure" >> $GITHUB_ENV
+          fi
         else
           # 生成随机端口并配置frpc
           max_attempts=10
@@ -140,31 +153,54 @@ jobs:
               echo "SSH_SETUP=success" >> $GITHUB_ENV
               break
             else
-              echo "错误：frpc启动失败!重试中..."
+              echo "错误:frpc启动失败!重试中..."
               pkill frpc
               attempts=$((attempts+1))
             fi
           done
 
           if [ $attempts -eq $max_attempts ]; then
-              echo "警告：尝试启动frpc $max_attempts 次仍然失败。请自行配置FRPC_CONFIG字段"
-              echo "SSH_SETUP=failure" >> $GITHUB_ENV
+            echo "警告:尝试启动frpc $max_attempts 次仍然失败。请自行配置FRPC_CONFIG字段"
+            echo "======================继续工作流======================="
+            echo "SSH_SETUP=failure" >> $GITHUB_ENV
           fi
         fi
         
-    - name: Suspend for custom
-      if: env.SSH_DEBUG == 'true'
+    - name: Pause workflow for custom
+      if: env.SSH_DEBUG == 'true' && env.SSH_SETUP == 'success'
       run: |
-        if [ "${{ env.SSH_SETUP }}" == 'success' ]; then
-          echo "暂停工作流,${{ env.SSH_TIME }}后将继续进行工作流.可使用pkill sleep命令提前继续工作流"
-          sleep ${{ env.SSH_TIME }}
-          echo "时间结束,继续进行工作流"
-        else
-          echo "frpc启动失败，跳过 suspend 步骤"
-        fi
-        
+#         插入gogogo命令
+          if [ ! -f /usr/bin/gogogo ]; then
+            echo '#!/bin/bash' > gogogo
+            echo 'sudo touch /home/runner/stop_signal' >> gogogo
+            sudo chmod a+x gogogo && sudo cp gogogo /usr/bin/
+            echo "================gogogo命令已加载!================"
+            echo "                                                "
+            echo "                                                "
+          else
+            echo "================gogogo命令已存在!================"
+            echo "                                                "
+            echo "                                                "
+          fi
+#         倒计时循环
+          echo -n -e "===================暂停工作流==================="
+          count=0  #分钟循环
+          while [ ! -f /home/runner/stop_signal ] && [ $count -lt ${{ env.SSH_TIME }} ]; do
+            inner_count=0  #秒钟循环
+            while [ $inner_count -lt 60 ]; do
+              echo -n -e "已过时间：$count分钟$inner_count秒,可使用 gogogo 命令提前继续工作流! \033[0K\r"
+              if [ -f /home/runner/stop_signal ]; then
+                break  # 如果文件存在，立即退出子循环
+              fi
+              sleep 1
+              inner_count=$((inner_count + 1))
+            done
+            count=$((count + 1))
+          done
+          # 循环结束后删除文件
+          sudo rm -f /home/runner/stop_signal
+                
     - name: Download package
-      if: always()
       working-directory: ./${{ env.BD_PROJECT }}
       run: |
         make download -j$(nproc)
@@ -173,86 +209,90 @@ jobs:
         df -h
 
     - name: Build firmware
-      if: always()
       working-directory: ./${{ env.BD_PROJECT }}
       run: |
         echo -e "$(nproc) thread build."
         make -j$(nproc) || make -j1 || make -j1 V=s | tee build.log
-        df -h
+        df -h 
 
     - name: Check compile
-      if: always()
       run: |
         cd ${{ env.BD_PROJECT }}/bin/targets/*/*
         if [ -n "$(ls *.img.gz)" ]; then
-          echo "COMPILE=success" >> $GITHUB_ENV
+          echo "BD_COMPILE=success" >> $GITHUB_ENV
           echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
           echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
           echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
           uppercase_string=$(echo "${{ env.BD_PROJECT }}" | tr '[:lower:]' '[:upper:]')
           echo "Uppercase_String=$uppercase_string" >> $GITHUB_ENV
           echo "===========编译成功,准备上传==========="
-          echo "=============生成文件列表============="
-          ls -lh | awk '{print $9, $5}'
-          echo "==============清理文件中============="
-          rm -rf packages *kernel.bin *rootfs* *.json *.tar.zst
-          sleep 2
-          echo "=============上传文件列表============="
-          ls -lh | awk '{print $9, $5}'
-          echo "===================================="
         else
-          echo "COMPILE=failure" >> $GITHUB_ENV
-          echo "===========编译失败,开启debug调试==========="
+          if [ "${{ env.SSH_SETUP }}" == 'success' ]; then
+            echo "BD_COMPILE=standby" >> $GITHUB_ENV
+            echo "===========编译失败,暂停工作流==========="
+            #### 留空等待添加编译失败通知功能
+          else
+            echo "===========编译失败,结束工作流==========="
+            exit 1
+          fi        
         fi
 
-    - name: Suspend for debug
-      if: always() && env.COMPILE == 'failure'
-      run: |
-        echo "COMPILE=standby" >> $GITHUB_ENV
-        if [ "${{ env.SSH_SETUP }}" == 'success' ]; then
-          echo "检测到编译失败,将暂停工作流${{ env.SSH_TIME2 }}以进行debug调试.调试完成后可使用pkill sleep命令提前继续工作流"
-          sleep ${{ env.SSH_TIME2 }}
-          echo "时间结束,继续进行工作流"
-        else
-          echo "检测到编译失败,但frpc未启动，跳过 debug 步骤,结束工作流"
-          echo "COMPILE=failure" >> $GITHUB_ENV
-          exit 1
-        fi
-
-    - name: Check compile again 
-      if: always() && env.COMPILE == 'standby'
+    - name: Pause workflow for debug
+      if: env.BD_COMPILE == 'standby'
       run: |
         cd ${{ env.BD_PROJECT }}/bin/targets/*/*
-        if [ -n "$(ls *.img.gz)" ]; then
-          echo "COMPILE=success" >> $GITHUB_ENV
-           echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
-           echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
-           echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
-           echo "===========编译成功,准备上传==========="
-           echo "=============生成文件列表============="
-           ls -lh | awk '{print $9, $5}'
-           echo "==============清理文件中============="
-           rm -rf packages *kernel.bin *rootfs* *.json *.tar.zst
-           sleep 2
-           echo "=============上传文件列表============="
-           ls -lh | awk '{print $9, $5}'
-           echo "===================================="
+#       插入gogogo命令
+        if [ ! -f /usr/bin/gogogo ]; then
+          echo '#!/bin/bash' > gogogo
+          echo 'sudo touch /home/runner/stop_signal' >> gogogo
+          sudo chmod a+x gogogo && sudo cp gogogo /usr/bin/
+          echo "================gogogo命令已加载!================"
+          echo "                                                "
+          echo "                                                "
         else
-          echo "COMPILE=failure" >> $GITHUB_ENV
-          echo "===========编译失败,结束工作流==========="
+          echo "================gogogo命令已存在!================"
+          echo "                                                "
+          echo "                                                "
+        fi
+#       倒计时循环
+        echo -n -e "===================暂停工作流==================="
+        count=0  #分钟循环
+        while [ ! -f /home/runner/stop_signal ] && [ $count -lt ${{ env.SSH_TIME2 }} ]; do
+          inner_count=0  #秒钟循环
+          while [ $inner_count -lt 60 ]; do
+            echo -n -e "已过时间：$count分钟$inner_count秒,可使用gogogo命令提前继续工作流! \033[0K\r"
+            if [ -f /home/runner/stop_signal ]; then
+              break  # 如果文件存在，立即退出子循环
+            fi
+            sleep 1
+            inner_count=$((inner_count + 1))
+          done
+#       检测是否编译成功
+          if [ -f /home/runner/stop_signal ]; then
+            if [ -n "$(ls *.img.gz)" ]; then
+              echo "BD_COMPILE=success" >> $GITHUB_ENV
+              echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
+              echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
+              echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
+              uppercase_string=$(echo "${{ env.BD_PROJECT }}" | tr '[:lower:]' '[:upper:]')
+              echo "Uppercase_String=$uppercase_string" >> $GITHUB_ENV
+              echo "===========编译成功,准备上传==========="
+              break
+            else
+              sudo rm -f /home/runner/stop_signal
+              echo "===========编译失败,继续暂停==========="
+              echo "BD_COMPILE=failure" >> $GITHUB_ENV
+            fi
+          fi
+          count=$((count + 1))        
+        done
+        if [ "${{ env.BD_COMPILE }}" == 'failure' ]; then
           exit 1
         fi
 
-    - name : Upload artifact
-      uses: actions/upload-artifact@main
-      if: always() && env.COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
-      with:
-        name: ${{ env.BD_PROJECT }}-firmware-${{ env.BD_TARGET }}-${{ env.DATE }}
-        path: ${{ env.FIRMWARE_PATH }} 
-        retention-days: 2
 
     - name: Upload Firmware To Release
-      if: always() && env.COMPILE == 'success' && env.UPLOAD_RELEASE == 'true'
+      if: env.BD_COMPILE == 'success' && env.UPLOAD_RELEASE == 'true'
       uses: ncipollo/release-action@main
       with:
         name: ${{ env.DATE }}_${{ env.Uppercase_String }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
@@ -271,16 +311,37 @@ jobs:
           - 🔑 默认密码: 空                
 
           ### 📒 插件列表:
-            ```
-            ShadowSocksR Plus+
-            PassWall
-            Openclash
-            Netdata
-            Autotimeset
-            AdGuard Home
-            Mosdns
-            DDNS-go
-            ZeroTier
-            Openvpn
-            应用中心(iStore)
-            ```
+          ```
+          ShadowSocksR Plus+
+          PassWall
+          Openclash
+          Netdata
+          Autotimeset
+          AdGuard Home
+          Mosdns
+          DDNS-go
+          ZeroTier
+          Openvpn
+          应用中心(iStore)
+          ```
+
+    - name: Organize files
+      if: env.BD_COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
+      working-directory: ${{ env.FIRMWARE_PATH }}
+      run: |
+        echo "=============生成文件列表============="
+        ls -lh | awk '{print $9, $5}'
+        echo "==============清理文件中============="
+        rm -rf packages *kernel.bin *rootfs* *.json *.tar.zst
+        sleep 2
+        echo "=============上传文件列表============="
+        ls -lh | awk '{print $9, $5}'
+        echo "===================================="
+
+    - name : Upload artifact
+      uses: actions/upload-artifact@main
+      if: env.BD_COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
+      with:
+        name: ${{ env.BD_PROJECT }}-firmware-${{ env.BD_TARGET }}-${{ env.DATE }}
+        path: ${{ env.FIRMWARE_PATH }} 
+        retention-days: 2
